apiVersion: v1
kind: Pod
metadata:
  name: django
  namespace: edu-anastasia-avakova
  labels:
    app: django
spec:
  containers:
    - name: django
      image: nastiaetstesha/django-site:82a3042
      ports:
        - containerPort: 80
      env:
        - name: ALLOWED_HOSTS
          value: "edu-anastasia-avakova.sirius-k8s.dvmn.org"
      volumeMounts:
        - name: ssl-cert-volume
          mountPath: /root/.postgresql/root.crt
          subPath: root.crt
          readOnly: true
  volumes:
    - name: ssl-cert-volume
      secret:
        secretName: psql-ssl-cert
        defaultMode: 384
