apiVersion: batch/v1
kind: CronJob
metadata:
  name: clearsessions
spec:
  schedule: "0 0 * * *"
  startingDeadlineSeconds: 300
  ttlSecondsAfterFinished: 60
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: clearsessions
              image: django_app
              imagePullPolicy: IfNotPresent
              command: ["python", "manage.py", "clearsessions"]
              envFrom:
                - secretRef:
                    name: django-secret
          restartPolicy: OnFailure
