apiVersion: batch/v1
kind: CronJob
metadata:
  name: clearsessions
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: clearsessions
              image: django_app
              imagePullPolicy: IfNotPresent
              command: ["python", "manage.py", "clearsessions"]
              env:
                - name: SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: django-secret
                      key: SECRET_KEY
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: django-secret
                      key: DATABASE_URL
          restartPolicy: OnFailure
