apiVersion: v1
kind: Pod
metadata:
  name: django-clearsessions
spec:
  restartPolicy: Never
  containers:
    - name: clearsessions
      image: django_app
      imagePullPolicy: IfNotPresent
      command: ["python", "manage.py", "clearsessions"]
      envFrom:
        - secretRef:
            name: django-secret
