apiVersion: v1
kind: Pod
metadata:
  name: django-app
  labels:
    app: django
    app.kubernetes.io/name: django
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: django-project
spec:
  containers:
    - name: django-container
      image: django_app
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
      env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: SECRET_KEY
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: DATABASE_URL
        - name: ALLOWED_HOSTS
          value: "192.168.49.2,127.0.0.1,localhost"
        - name: DEBUG
          value: "False"
